Algoritmo AREA_DE_UN_TRIANGULO
	DEFINIR BASE, ALTURA, AREA COMO REAL
	ESCRIBIR "INGRESE BASE:" ; LEER BASE
	ESCRIBIR " INGRESE ALTURA:" ; LEER ALTURA
	
	AREA = (BASE * ALTURA ) / 2
	ESCRIBIR "AREA = ", area 
	
FinAlgoritmo
